I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    h2 "sayounara"
Exception: Sayer 'h2' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    h2 "sayounara"
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'h2' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
TA GENSHIKEN 1.0
Tue Oct 11 15:02:08 2022
